### ISSUE TITLE
Publish to Bintray when convenient

### ISSUE THREAD

**Issue by KenSuenobu** [KenSuenobu/scattersphere#107]
No milestone, as this could take days or weeks.  I've already tried this on both Sonatype and Bintray, and being open source projects, I'm not expecting help.  I need someone who's had experience here to help me out, otherwise, this project will not be uploaded to Maven Central.

I'm not about to lose any more hair over this.

**Comment by KenSuenobu** [comment]
@ngbinh going to try and get this submitted to Bintray this weekend.  Pretty sure I know what I did wrong... at least, I hope I know.

**Comment by ngbinh** [comment]
Thanks for trying that. I would be able to help with sbt but I am not that familiar with maven.

**Comment by KenSuenobu** [comment]
Okay, still having a problem pushing to Bintray.  I've got a support ticket open with Jfrog, and hopefully they'll fix their out-of-date documentation.  Followed the docs to the letter, and it fails to deploy.

**Comment by KenSuenobu** [comment]
Published to Bintray!

**Comment by ngbinh** [comment]
can you publish the link here? Thanks
