### ISSUE TITLE
Create a shell task

### ISSUE THREAD

**Issue by KenSuenobu** [KenSuenobu/scattersphere#44]
Create a task that can be easily used for invoking a shell command.

**Comment by ngbinh** [comment]
while at it, please consider https://github.com/brettwooldridge/NuProcess instead of `ProcessBuilder`

**Comment by KenSuenobu** [comment]
I will definitely review it.  We've done some pretty awesome stuff with `ProcessBuilder`, and made sure that it works with cross-platform, which is the most important piece to this task.  If this works well, I might end up using it.  If you want, once the code is in place, I can assign you as a reviewer.

**Comment by KenSuenobu** [comment]
It's a great application in theory, but it's going to take a lot of work to get it working with Scala.  Probably more than is intended for this library.  The `ShellTask` task can be overridden using a `trait`, so I'm not worried.  If someone wants to introduce a `NuShellTask`, that is fine.

**Comment by KenSuenobu** [comment]
I've decided to forego using this library, as I want to keep things simple.  I can leave it up to other developers to implement their own version of a process handler for the `ShellTask`.

**Comment by KenSuenobu** [comment]
Code finished.
