### ISSUE TITLE
Publish artifact to maven central

### ISSUE THREAD

**Issue by ngbinh** [KenSuenobu/scattersphere#81]
Somehow I cannot find any artifact for scattersphere on MavenCentral.

Thanks

**Comment by KenSuenobu** [comment]
Work from ticket #94 completed, related to this work.

**Comment by KenSuenobu** [comment]
In progress!

**Comment by KenSuenobu** [comment]
@ngbinh Regard: https://issues.sonatype.org/browse/OSSRH-40617

**Comment by ngbinh** [comment]
Thanks.

@KenSuenobu you can also publish to bintray https://bintray.com  .From there,you can link to Maven central easily

**Comment by KenSuenobu** [comment]
Work linking to #105 as well ... which has been completed.

**Comment by KenSuenobu** [comment]
About ready to give up.  I've tried Sonatype and Bintray and I'm getting odd errors from both with an Unauthorized message.  I've followed both guides to the letter, and I'm still not getting anywhere.  I'm going to move on to other tickets, and move this to another milestone.  This is just nuts.
